import {
  Award,
  BarChart3,
  Bot,
  Boxes,
  Brain,
  BrainCircuit,
  Braces,
  Car,
  Code2,
  Cog,
  Cpu,
  Database,
  Eye,
  Flame,
  FlaskConical,
  Globe,
  GraduationCap,
  Grid3x3,
  HeartPulse,
  Hexagon,
  Layers,
  Library,
  LineChart,
  MessagesSquare,
  NotebookPen,
  Palette,
  Radar,
  ScanEye,
  ShieldCheck,
  Sparkles,
  SquareCode,
  Table2,
  Terminal,
  UserCheck,
  Wallet,
} from "lucide-react";

const MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  brain: Brain,
  sparkles: Sparkles,
  layers: Layers,
  eye: Eye,
  messages: MessagesSquare,
  code: Code2,
  database: Database,
  grid: Grid3x3,
  table: Table2,
  hexagon: Hexagon,
  flame: Flame,
  boxes: Boxes,
  scan: ScanEye,
  flask: FlaskConical,
  globe: Globe,
  palette: Palette,
  braces: Braces,
  "square-code": SquareCode,
  notebook: NotebookPen,
  shield: ShieldCheck,
  "scan-face": ScanEye,
  "heart-pulse": HeartPulse,
  car: Car,
  wallet: Wallet,
  "line-chart": LineChart,
  "user-check": UserCheck,
  library: Library,
  radar: Radar,
  badge: Award,
  terminal: Terminal,
  cog: Cog,
  graduation: GraduationCap,
  "brain-circuit": BrainCircuit,
  bot: Bot,
  cpu: Cpu,
  "bar-chart": BarChart3,
};

export default function Icon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Cmp = MAP[name] ?? Sparkles;
  return <Cmp className={className} />;
}
